name: Laravel CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, bcmath, xml, gd, zip

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist

      - name: Copy env and generate key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run migrations
        env:
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: secret
          DB_HOST: 127.0.0.1
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --no-coverage
